name: NextJS changes deploy matetransport.com

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: GIT pulling from github repository
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      with:
        source: "."
        target: "/home/front/matetransport.com"

    - name: Command using from script
      uses: appleboy/ssh-action@master
      env:
        DISABLE_ESLINT_PLUGIN: "true"
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        script_stop: true
        script: |
          git --work-tree=/home/front/matetransport.com --git-dir=/home/front/matetransport.com/.git clean -f .
          npm --prefix /home/front/matetransport.com/ install /home/front/matetransport.com/
          npm --prefix /home/front/matetransport.com/ run build
          sh /home/devops/matelog_front.sh "${{ github.event.head_commit.message }}"
          pm2 reload matetransport.com
